### PR TITLE
Complete Type definitions

### PR DESCRIPTION
**Pull request by sisou**
All. Types. Done.

### CODE REVIEW

**Comment by sisou** [comment]
Now validated that it still works with `keyguard-next` and `accounts`.

**Review by Bettelstab — CHANGES_REQUESTED** [review]
It would be nice to put static fields and methods first.

**Comment by sisou** [comment]
I followed the order of the declarations in the code. I know that's not a good reason, but at least it's consistent :P

**Comment by Bettelstab** [comment]
Well, with the tslint config we use in the other projects, it would complain.

**Review by Bettelstab — APPROVED** [review]

**Pull request merged**
